### ISSUE TITLE
It has error in this model 

### ISSUE THREAD

**Issue by lnye007** [OskarSigvardsson/unity-quickhull#2]
input data(X,Y,Z):
-0.06270732 , 0.03174151 , 0.025
-0.06097341 , 0.03174151 , 0.025
-0.06270732 , 0.03174151 , 0
-0.06097341 , 0.03174151 , 0
-0.05804581 , 0.03174151 , 0.025
0.0850401 , 0.03174151 , 0.025
-0.05804581 , 0.03174151 , 0
0.0850401 , 0.03174151 , 0
-0.06874499 , -0.05041299 , 0.025
-0.06874499 , 0.03174151 , 0.025
-0.06874499 , -0.05041299 , 0
-0.06874499 , 0.03174151 , 0
0.0850401 , -0.05041299 , 0.025
0.0850401 , -0.05041299 , 0
-0.06563492 , 0.03174151 , 0
-0.06563492 , 0.03174151 , 0.025
-0.06558505 , 0.03136266 , 0.025
-0.06520618 , 0.03070645 , 0.025
-0.06543881 , 0.03100961 , 0.025
-0.06092353 , 0.03136266 , 0.025
-0.06313606 , 0.03070645 , 0.025
-0.0607773 , 0.03100961 , 0.025
-0.06290343 , 0.03100961 , 0.025
-0.06275719 , 0.03136266 , 0.025
-0.05809569 , 0.03136266 , 0.025
-0.05824192 , 0.03100961 , 0.025
-0.06417112 , 0.03027771 , 0.025
-0.06454998 , 0.03032759 , 0.025
-0.06490302 , 0.03047382 , 0.025
-0.05847454 , 0.03070645 , 0.025
-0.05877771 , 0.03047382 , 0.025
-0.05913075 , 0.03032759 , 0.025
-0.05950961 , 0.03027771 , 0.025
-0.05988847 , 0.03032759 , 0.025
-0.06343922 , 0.03047382 , 0.025
-0.06379226 , 0.03032759 , 0.025
-0.06054467 , 0.03070645 , 0.025
-0.06024151 , 0.03047382 , 0.025
-0.05824192 , 0.03100961 , 0
-0.05809569 , 0.03136266 , 0
-0.06290343 , 0.03100961 , 0
-0.06313606 , 0.03070645 , 0
-0.06343922 , 0.03047382 , 0
-0.06275719 , 0.03136266 , 0
-0.06092353 , 0.03136266 , 0
-0.0607773 , 0.03100961 , 0
-0.06054467 , 0.03070645 , 0
-0.05913075 , 0.03032759 , 0
-0.05877771 , 0.03047382 , 0
-0.05847454 , 0.03070645 , 0
-0.06558505 , 0.03136266 , 0
-0.06543881 , 0.03100961 , 0
-0.06520618 , 0.03070645 , 0
-0.06490302 , 0.03047382 , 0
-0.06454998 , 0.03032759 , 0
-0.06417112 , 0.03027771 , 0
-0.06379226 , 0.03032759 , 0
-0.06024151 , 0.03047382 , 0
-0.05988847 , 0.03032759 , 0
-0.05950961 , 0.03027771 , 0

**Comment by SlimeQ** [comment]
I think this is probably related to [the other issue](https://github.com/OskarSigvardsson/unity-quickhull/issues/1)

You have 6 planar points on the plane (x, 0.03174151 , 0.025)

**Comment by OskarSigvardsson** [comment]
This has now been resolved.
