### ISSUE TITLE
Non-coplanar points being identified as coplanar

### ISSUE THREAD

**Issue by Kimbatt** [OskarSigvardsson/unity-quickhull#3]
I have the following point set:
```
a = (-0.125, 0.125, -0.125)
b = (-0.149, 0.125, -0.125)
c = (-0.125, 0.125, -0.192)
d = (-0.125, 0.0, -0.125)
```

![image](https://user-images.githubusercontent.com/29901058/73836554-d399c200-480f-11ea-8eea-99874c8f9408.png)

When finding the initial points for the hull generation, these points are identified as coplanar, so the generation fails.  

The problem probably comes from the input point coordinates being smaller than 1, so the cross product becomes smaller and smaller (eventually they become smaller than epsilon).

Maybe this could be fixed by taking the normalized vector after the cross product (or choose a different method to calculate if points are coplanar)?
(I haven't checked if this solution is actually correct, but it seems to be working)
```csharp
bool AreCoplanar(Vector3 a, Vector3 b, Vector3 c, Vector3 d)
{
    var n1 = Cross(c - a, c - b).normalized;
    var n2 = Cross(d - a, d - b).normalized;

    return AreCollinear(Vector3.zero, n1, n2);
}
```

**Comment by OskarSigvardsson** [comment]
I haven't spent a lot of time thinking about this, but that seems like a reasonable solution. The only issue I can see is if the points are collinear ((a,b,c) or (a,b,d)), then the cross product would be zero and the normalization would be undefined (division by zero). But you can fix that by checking if they're collinear first, I guess (I don't remember if I do this, but it wouldn't be hard to add). 

I'll see if I can take some time to take a look at this soon, and see if I can figure out a solution. If test it properly and this solution works, I'd be happy to accept a pull request.

**Comment by OskarSigvardsson** [comment]
@Kimbatt Hey, sorry for the delay, just got around to looking at this now. I looked at this issue now, and your solution seems just fine. I [implemented a slightly different version](https://github.com/OskarSigvardsson/unity-quickhull/commit/38896b17dcc7f674d2d126e983960052b32388c6?diff=split#diff-1d7cd58c7e7f3ef844ed4634048bfff1R937) of it that does some extra checks to make sure the magnitude of either vector isn't zero (which is slightly defensive, but given how I wrote the GenerateInitialHull function, is possible), but pretty much that idea. 

Please test if you have time, but I'm going to close this issue now. Thanks for the report!
